### ISSUE TITLE
中国版米游社`salt`

### ISSUE THREAD

**Issue by Kamisato-Ayaka-233** [Kamisato-Ayaka-233/mihoyo-api-collect#1]
# 可用的`salt`

**在需要验证请求头的API**

| BBS`salt` | API`salt` | 米游社APP版本 |
| ----- | ------------ | ---------- |
| dZAwGk4e9aC0MXXItkwnHamjA1x30IYw | xV8v4Qu54lUKrEYFZkJhB8cuOh9Asafs | 2.44.1 |
| YVEIkzDFNHLeKXLxzqCA9TzxCpWwbIbk | n0KjuIrKgLHh08LWSCYP0WXlVXaYvV64 | 2.36.1 |
| ZSHlXeQUBis52qD1kEgKt5lUYed4b7Bb | N50pqm7FSy2AkFz2B3TqtuZMJ5TOl3Ep | 2.35.2 |
| z8DRIUjNDT7IT5IZXvrUAxyupA1peND9 | 9nQiU3AV0rJSIBWgdynfoGMGKaklfbM7 | 2.34.1 |
| dWCcD2FsOUXEstC5f9xubswZxEeoBOTc | ulInCDohgEs557j0VsPDYnQaaz6KJcv5 | 2.28.1 |

## 应该使用哪个`salt`？

取决于请求头的`x-rpc-client_type`。

* 当`x-rpc-client_type`为`2`时，使用BBS`salt`，配合`x-rpc-client_type`为`2`使用的`DS`算法
* 当`x-rpc-client_type`为`5`时，使用API`salt`，配合`x-rpc-client_type`为`5`使用的`DS`算法。

`x-rpc-client_type`的值会在需要验证请求头的API进行标识。

如果某个API需要独有的`salt`、`DS`算法等，应标识。

# `salt`位置

## `x-rpc-client_type`为`2`时使用的`salt`

Hook`com.mihoyo.hyperion.net.bbbbb.a2222`并记录参数值即可获得。

可使用工具：LSPosed模块（例如“[SimpleHook](https://github.com/littleWhiteDuck/SimpleHook)”模块）、[Frida](https://github.com/frida/frida-tools)（米游社有Anti-Frida处理） 等

在`libdddd.so`中寻找`com.mihoyo.hyperion.net.aaaaa.a2222`的来源函数。

可使用工具：IDA Pro 等

## `x-rpc-client_type`为`5`时使用的`salt`

在`libxxxx.so`中寻找`com.mihoyo.hyperion.net.aaaaa.a2222`的来源函数。

可使用工具：IDA Pro 等

# `DS`生成算法的位置

_注：下文简称“`DS`算法”。_

_截至2.44.1版本_

`DS`算法的位置：

`com.mihoyo.platform.account.sdk.network.RequestUtils.createSign`

初步推测为注册米游社账号使用的。

该函数内也有1个`salt`。

`com.mihoyo.hyperion.net.bbbbb.a2222`

*来自`libdddd.so`*

 `x-rpc-client_type`为`2`时使用的`DS`算法。

因为该函数直接传入了`salt`，因此Hook该函数并记录参数值即可获得`x-rpc-client_type`为`2`时使用的`salt`。

参数：`salt`

返回：`DS`

`com.mihoyo.hyperion.net.aaaaa.a2222`

*来自`libxxxx.so`*

 `x-rpc-client_type`为`5`时使用的`DS`算法。

参数：POST请求的数据，GET请求的URL参数

返回：`DS`

`com.mihoyo.hyperion.net.aaaaa.b5555`

*来自`libxxxx.so`*

未知用途，尝试Hook该函数，但是并程序并没有调用该函数生成`DS`。

参数：POST请求的数据，GET请求的URL参数

返回：`DS`

**Comment by Kamisato-Ayaka-233** [comment]
为了好康，就关闭这个Issue了。

可以在固定Issue上康。

**Comment by Kamisato-Ayaka-233** [comment]
现在看来这个描述还有亿点错误……

**Comment by fanlu** [comment]
现在米游社更新到2.51.1了

**Comment by Kamisato-Ayaka-233** [comment]
> 现在米游社更新到2.51.1了

这倒没事，哪个版本不重要。只需要请求头`x-rpc-app_version`配合其版本对应的`salt`来生成`DS`便可。

**Comment by stuchilde** [comment]
x-rpc-client_type为1要怎么弄呢？

**Comment by MoRanYue** [comment]
> x-rpc-client_type为1要怎么弄呢？

emm，这是什么API呀？

**Comment by stuchilde** [comment]
米游社ios客户端抓包，看到header中的x-rpc-client_type都是1

**Comment by stuchilde** [comment]
![image](https://github.com/UIGF-org/mihoyo-api-collect/assets/18589232/82a7db66-2406-4c5a-8050-6c4047b6af7a)

**Comment by MoRanYue** [comment]
> ![image](https://private-user-images.githubusercontent.com/18589232/292624048-82a7db66-2406-4c5a-8050-6c4047b6af7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzIwNDgsIm5iZiI6MTcwMzMzMTc0OCwicGF0aCI6Ii8xODU4OTIzMi8yOTI2MjQwNDgtODJhN2RiNjYtMjQwNi00YzVhLTgwNTAtNmM0MDQ3YjZhZjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDExNDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwM2VmYTA2ZmRkOTYxYTA0NDg1OTYzYjhhZDFjMWJhMjgwMmJkZTc5YTJkZWExNzczZmY4ZWFkM2ZiYzA1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7U4WEC5TzI_OfGRo2AZEO8wykLt_6b7XhT2JGbnOt2w)

emm，与安卓的生成方法相同呀

**Comment by stuchilde** [comment]
用4x的salt配合DS2算法生成的DS请求还是报错`invalid request`，还有啥需要注意的么？

**Comment by MoRanYue** [comment]
> 用4x的salt配合DS2算法生成的DS请求还是报错`invalid request`，还有啥需要注意的么？

emm，将`x-rpc-client_type`的值设为`5`嘛

**Comment by stuchilde** [comment]
都试了还是不行

**Comment by MoRanYue** [comment]
> 都试了还是不行

API的URL是什么呀？

所有的`salt`都试过了嘛？

**Comment by stuchilde** [comment]
https://api-takumi-record.mihoyo.com/game_record/card/api/getGameRecordCard

**Comment by stuchilde** [comment]
https://api-takumi-record.mihoyo.com/game_record/card/api/getGameRecordCard?uid=xxxx
这个接口，还有个uid参数
```
def get_ds():
    salt = "xV8v4Qu54lUKrEYFZkJhB8cuOh9Asafs"
    t = 1703331929
    r = "wd7tTm"  # 任意六位随机字符
    ds_str = f"salt={salt}&t={t}&r={r}&b=&q=uid=xxxx"
    ds = hashlib.md5(ds_str.encode(encoding='UTF-8')).hexdigest()
    return f"{t},{r},{ds}"
```

**Comment by MoRanYue** [comment]
> https://api-takumi-record.mihoyo.com/game_record/card/api/getGameRecordCard?uid=xxxx
> 这个接口，还有个uid参数
> ```
> def get_ds():
>     salt = "xV8v4Qu54lUKrEYFZkJhB8cuOh9Asafs"
>     t = 1703331929
>     r = "wd7tTm"  # 任意六位随机字符
>     ds_str = f"salt={salt}&t={t}&r={r}&b=&q=uid=xxxx"
>     ds = hashlib.md5(ds_str.encode(encoding='UTF-8')).hexdigest()
>     return f"{t},{r},{ds}"
> ```

a，抱歉，弄错了呀。

根据文档，这个API应该这样使用呀。

![Screenshot_2023-12-23-20-28-53-782_com.github.android-edit.png](https://github.com/UIGF-org/mihoyo-api-collect/assets/84905594/0c9b615e-ff05-43be-be82-4c9390db9de6)

**Comment by CainLuo** [comment]
@MoRanYue 有个疑问，4X和6X是啥意思？

**Comment by MoRanYue** [comment]
> @MoRanYue 有个疑问，4X和6X是啥意思？

emmm，它们，分别是2种，不同的Salt类型呀。只是因为，在混淆的APK代码中，它们分别被叫做“4x”“6x”，因此而命名呀
